spring.application.name=Aventix
spring.datasource.url=jdbc:mysql://localhost:3306/aventix_db
spring.datasource.username=root
spring.datasource.password=Xy9!qT3vM5@z
server.port=8080
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

keycloak.auth-server-url=http://localhost:8180/auth
keycloak.realm=UsersManagement
keycloak.resource=my-spring-app
keycloak.credentials.secret=d8132036-891a-4612-9b5f-ef260690b757
keycloak.bearer-only=true
keycloak.ssl-required=external
keycloak.use-resource-role-mappings=true
keycloak.public-client=false
spring.security.enabled=false
keycloak.enabled=false

