spring.application.name=Aventix
spring.datasource.url=jdbc:mysql://localhost:3306/aventix
spring.datasource.username=root
spring.datasource.password=admin
server.port=8080
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

#Configuration Keycloak côté backend
keycloak.auth-server-url=https://<your-keycloak-server>/realms/<your-realm>/protocol/openid-connect
keycloak.realm=<your-realm>
keycloak.resource=<your-client-id>
keycloak.credentials.secret=<your-client-secret>
keycloak.use-resource-role-mappings=true
keycloak.bearer-only=true
keycloak.security-constraints[0].authRoles[0]=user
keycloak.security-constraints[0].url-pattern=/api/*

